services:
  - type: web
    name: whatsapp-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: WHATSAPP_API_KEY
        value: "your_whatsapp_api_key_here"
      - key: WHATSAPP_PHONE_NUMBER_ID
        value: "your_phone_number_id_here"
      - key: WHATSAPP_VERIFICATION_TOKEN
        value: "your_verification_token_here"
